config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :friends
  resources :friend_requests
  resources :likes,    only: %i[create destroy]
  resources :posts,    only: %i[create destroy show] do
    resources :comments, only: %i[create destroy]
  end
  root to: 'static_pages#home'
end

app/models/user.rb
class User < ApplicationRecord
  after_create :welcome_email

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, foreign_key: 'author_id'
  has_many :friend_requests, dependent: :destroy
  has_many :pending_friends, through: :friend_requests, source: :friend
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships
  has_many :likes, dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy

  def welcome_email
    WelcomeMailer.welcome_email(self).deliver
  end

  def is_friend?(another_user)
    friends.include?(another_user)
  end

  def pending?(another_user)
    friend_requests.find_by(friend_id: another_user.id)
  end

  def remove_friend(friend)
    friends.destroy(friend)
  end

  def find_like(post_id)
    likes.where(post_id: post_id, user_id: id)
  end

  def liked?(post_id)
    likes.where(post_id: post_id, user_id: id).any?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.paginate(page: params[:page])
  end

  def index
    @users = User.where.not(id: current_user.id).paginate(page: params[:page])
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for given user.
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.first_name, class: 'gravatar')
  end
end

app/views/users/index.html.erb
<h1>All users</h1>

<ul>
  <% @users.each do |user| %>
    <li>
      <%= link_to "#{user.first_name.capitalize} #{user.last_name.capitalize}", user_path(user.id) %>
      <% if current_user.is_friend?(user) %>
        <h3>Friend</h3>
      <% elsif current_user.pending?(user) %>
        <%= link_to 'Cancel', friend_request_path(user.id), method: :delete, class: 'btn btn-danger' %>
      <% else %>
        <%= form_for current_user.friend_requests.build(friend: user) do |f| %>
          <%= f.hidden_field :friend_id  %>
          <button class='btn btn-info'>Add Friend</button>
        <% end %>
      <% end %>
    </li>
  <% end %>
</ul>
<%= will_paginate @users %>

app/views/users/show.html.erb
<div>

  <!-- User name -->
  <h1>
    <%= gravatar_for @user %>
    <%= @user.first_name.capitalize %>
    <%= @user.last_name.capitalize %><br/>
  </h1>

  <!-- Send/cancel friend request -->
  <% if current_user.is_friend?(@user) %>
    <%= link_to 'Unfriend', friend_path(@user.id), method: :delete,
                class: 'btn btn-danger',
                data: { confirm: 'Are you sure?'}%>
  <% elsif current_user.pending?(@user) %>
    <%= link_to 'Pending', friend_request_path(@user.id), method: :delete,
                class: 'btn btn-danger' %>
  <% else %>
    <%= form_for current_user.friend_requests.build(friend: @user) do |f| %>
      <%= f.hidden_field :friend_id  %>
      <button class='btn btn-info'>Add Friend</button>
    <% end %>
  <% end %>
</div>

<!-- Posts -->
<aside>
  <h3>Posts (<%= @user.posts.count %>)</h3>
  <% @posts.each do |post| %>
    <li id="<%= post.id %>">
      <h4><%= post.content %></h4>
      Posted <%= time_ago_in_words(post.created_at) %> ago.
      <%= link_to 'View', posts_path(post.id) %>
    </li>
  <% end %>
  <%= will_paginate @posts %>
</aside>