config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :friends
  resources :friend_requests
  resources :likes,    only: %i[create destroy]
  resources :posts,    only: %i[create destroy show] do
    resources :comments, only: %i[create destroy]
  end
  root to: 'static_pages#home'
end

app/models/post.rb
class Post < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :likes, dependent: :destroy
  has_many :comments
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :correct_user, only: :destroy

  def new
    @comment = Comment.new(post_id: params[:id])
  end

  def create
    @post = current_user.posts.build(posts_params)
    if @post.save
      flash[:success] = 'Post created!'
      redirect_to root_path
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @post.destroy
    flash[:success] = 'Post deleted.'
    redirect_to request.referrer || root_url
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.paginate(page: params[:page])
    @comment = current_user.comments.new
    @comment.post_id = @post.id
  end

  private

  def posts_params
    params.require(:post).permit(:content)
  end

  def correct_user
    @post = current_user.posts.find(params[:id])
    redirect_to root_url if @post.nil?
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/show.html.erb
<div>
  <!-- Author Information -->
  <h2>
    <%= @post.author.first_name.capitalize %>
    <%= @post.author.last_name.capitalize %>
  </h2>

  <!-- Post Content -->
  <h4><%= @post.content %></h4>

  <!-- Create comment -->
  <h3>Post a comment</h3>
  <%= render 'shared/comment_form', collection: @post.comments %>

  <!-- Comment count -->
  <h3>Comments(<%= @comments.count %>)</h3>

  <!-- Comment display -->
  <% @comments.desc.each do |comment| %>
    <li class="<%= comment.id %>">
      <h3>
        <%= comment.author.first_name.capitalize %>
        <%= comment.author.last_name.capitalize  %>
      </h3>
      <h4><%= comment.content %></h4>
      <span>
        Commented <%=time_ago_in_words(comment.created_at) %> ago.
      </span>
      <% if comment.author_id == current_user.id %>
        <%= link_to 'Delete', post_comment_path(@post.id, comment.id),
                    method: :delete, class: 'text-danger' %>
      <% end %>
    </li>
  <% end %>
</div>