config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :friends
  resources :friend_requests
  resources :likes,    only: %i[create destroy]
  resources :posts,    only: %i[create destroy show] do
    resources :comments, only: %i[create destroy]
  end
  root to: 'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  scope :desc, -> { order(created_at: :desc)}
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post

end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'

  validate :not_friends
  validate :not_pending
  validate :not_self
  validates :user, presence: true
  validates :friend, presence: true, uniqueness: { scope: :user }

  def accept
    user.friends << friend
    destroy
  end

  private

  def not_friends
    errors.add(:friend, 'is already added') if user.friends.include?(friend)
  end

  def not_pending
    errors.add(:friend, 'already requested friendship') if friend.pending_friends.include?(user)
  end

  def not_self
    errors.add(:friend, "can't be equal to user") if user == friend
  end
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  after_create :create_inverse_relationship
  after_destroy :destroy_inverse_relationship

  belongs_to :user
  belongs_to :friend, class_name: 'User'

  validate :not_self
  validates :user, presence: true
  validates :friend, presence: true, uniqueness: { scope: :user }

  private

  def create_inverse_relationship
    friend.friendships.create(friend: user)
  end

  def destroy_inverse_relationship
    friendship = friend.friendships.find_by(friend: user)
    friendship&.destroy
  end

  def not_self
    errors.add(:friend, "can't be equal to user") if user == friend
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user, presence: true

end

app/models/post.rb
class Post < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :likes, dependent: :destroy
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  after_create :welcome_email

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, foreign_key: 'author_id'
  has_many :friend_requests, dependent: :destroy
  has_many :pending_friends, through: :friend_requests, source: :friend
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships
  has_many :likes, dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy

  def welcome_email
    WelcomeMailer.welcome_email(self).deliver
  end

  def is_friend?(another_user)
    friends.include?(another_user)
  end

  def pending?(another_user)
    friend_requests.find_by(friend_id: another_user.id)
  end

  def remove_friend(friend)
    friends.destroy(friend)
  end

  def find_like(post_id)
    likes.where(post_id: post_id, user_id: id)
  end

  def liked?(post_id)
    likes.where(post_id: post_id, user_id: id).any?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: :destroy

  def create
    @comment = current_user.comments.new(comment_params)
    @comment.post_id = params[:post_id]
    if @comment.save!
      flash[:success] = 'Comment posted!'
      redirect_to post_path(@comment.post_id)
    else
      flash.now[:notice] = 'Comment could not save.'
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @comment.destroy
    redirect_back(fallback_location: root_url)
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id, :author_id)
  end

  def set_comment
    @comment = Comment.find_by(post_id: params[:post_id], author_id: current_user.id)
  end
end

app/controllers/friends_controller.rb
# frozen_string_literal: true

class FriendsController < ApplicationController
  before_action :set_friend, only: :destroy

  def index
    @friends = current_user.friends.paginate(page: params[:page])
  end

  def destroy
    current_user.remove_friend(@friend)
    redirect_back(fallback_location: root_path)
  end

  private

  def set_friend
    @friend = current_user.friends.find(params[:id])
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  before_action :set_like, only: :destroy

  def create
    @like = current_user.likes.new(post_id: params[:id])
    if @like.save && !current_user.liked?(params[:id])
      flash[:success] = 'Like saved'
      redirect_back(fallback_location: root_path)
    else
      flash.now[:danger] = 'Like not saved'
      redirect_to root_path
      puts 'doesnt work'
    end
  end

  def destroy
    @like.destroy
    redirect_back(fallback_location: root_path)
  end

  private

  def set_like
    @like = Like.find_by(post_id: params[:id], user_id: current_user.id)
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :correct_user, only: :destroy

  def new
    @comment = Comment.new(post_id: params[:id])
  end

  def create
    @post = current_user.posts.build(posts_params)
    if @post.save
      flash[:success] = 'Post created!'
      redirect_to root_path
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @post.destroy
    flash[:success] = 'Post deleted.'
    redirect_to request.referrer || root_url
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.paginate(page: params[:page])
    @comment = current_user.comments.new
    @comment.post_id = @post.id
  end

  private

  def posts_params
    params.require(:post).permit(:content)
  end

  def correct_user
    @post = current_user.posts.find(params[:id])
    redirect_to root_url if @post.nil?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.paginate(page: params[:page])
  end

  def index
    @users = User.where.not(id: current_user.id).paginate(page: params[:page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
  def friend_request_count
    @incoming = FriendRequest.where(friend: current_user)
    @incoming.count || 0
  end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for given user.
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.first_name, class: 'gravatar')
  end
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Fakebook', root_path, class: 'navbar-brand' %>
    </div>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= link_to 'Friends', friends_path %>
          </li>
          <li>
            <%= link_to "Friend Requests(#{friend_request_count})", friend_requests_path %>
          </li>
          <li>
            <%= link_to 'Users', users_path %>
          </li>
          <li>
            <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
          </li>
        <% else %>
          <li>
            <%= link_to 'Log in', new_user_session_path %>
          </li>
        <% end %>
      </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fakebook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag :div, value, class: "flash #{key}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_comment_form.html.erb
<%= form_for [ @post, @comment ] do |f| %>
  <%= f.text_area :content, placeholder: 'What are your thoughts?' %><br/>
  <%= f.submit 'Comment', class: 'btn btn-primary' %>
<% end %>

app/views/shared/_like_button.html.erb
<% if current_user.liked?(item.id) %>
  <%= link_to '', like_path(item.id), method: :delete,
              class: 'glyphicon glyphicon-thumbs-up primary' %>
<% else %>
  <%= link_to '', likes_path(id: item.id), method: :post,
              class:'glyphicon glyphicon-thumbs-up',
              style: 'color:grey' %>
<% end %>

app/views/shared/_post_form.html.erb
<div>
  <%= form_for @post  do |f| %>
    <%= f.text_area :content, placeholder:"What's new?" %><br />
    <%= f.submit 'Post', class: 'btn btn-primary' %>
  <% end %>
</div>